# Generated by Django 3.2.6 on 2021-08-12 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='active_code',
            new_name='activation_code',
        ),
    ]
