# Generated by Django 3.2.6 on 2021-08-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_orderitems_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('open', 'Открытый'), ('in_progress', 'в обработке'), ('canceled', 'Отмененный'), ('finished', 'Завершенный')], default='open', max_length=20),
        ),
    ]
